name: Deploy brunnerliv.io
on:
  push:
    branches:
      - master
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check out brunnerliv.io
        uses: actions/checkout@master
        with:
          repository: brunnerlivio/brunnerliv.io
          path: brunnerliv.io
      - run: |
          cd brunnerliv.io
          git submodule update --remote --init --recursive
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@devel
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: brunnerliv.io/
          destination-github-username: 'brunnerlivio'
          destination-repository-name: 'brunnerliv.io'
          user-name: brunnerlivio
          user-email: livio.brunner.lb1@gmail.com
          commit-message: Update submodules
          target-branch: master
