name: Deploy brunnerliv.io
on:
  push:
    branches:
      - master
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check out brunnerliv.io
        uses: actions/checkout@master
        with:
          repository: brunnerlivio/brunnerliv.io
          path: brunnerliv.io
      - run: |
          cd brunnerliv.io
          git config --global user.name 'Github Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git submodule update --remote --init --recursive
          git add -A .
          git commit -m "Update submodule"
          git push --force "https://${{ secrets.API_TOKEN_GITHUB }}@github.com/BrunnerLivio/brunnerliv.io.git" master:master
          
